#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
OUT_DIR="${1:-$ROOT_DIR/target/docs-site}"
API_DIR="$OUT_DIR/api"

rm -rf "$OUT_DIR"
mkdir -p "$API_DIR"

echo "[1/3] Building rustdoc"
rm -rf "$ROOT_DIR/target/doc"
cargo doc --workspace --no-deps

echo "[2/3] Copying rustdoc output"
cp -a "$ROOT_DIR/target/doc/." "$API_DIR/"

echo "[3/3] Generating top page"
cat <<'TOPPAGE' >"$OUT_DIR/index.html"
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>ad-tensors-rs docs</title>
    <style>
      :root {
        --bg: #f6f8fb;
        --fg: #14213d;
        --muted: #3c4a6b;
        --accent: #005bb5;
        --card: #ffffff;
        --line: #d9e1ef;
      }
      body {
        margin: 0;
        color: var(--fg);
        font-family: "IBM Plex Sans", "Segoe UI", sans-serif;
        background: radial-gradient(circle at top right, #eef4ff, var(--bg) 60%);
      }
      main {
        max-width: 860px;
        margin: 0 auto;
        padding: 44px 20px 56px;
      }
      h1 {
        margin: 0 0 10px;
        font-size: 2rem;
      }
      p {
        margin: 0 0 10px;
        color: var(--muted);
        line-height: 1.55;
      }
      .card {
        margin-top: 24px;
        border: 1px solid var(--line);
        border-radius: 10px;
        background: var(--card);
        padding: 16px;
      }
      .card h2 {
        margin: 0 0 8px;
        font-size: 1.1rem;
      }
      .card a {
        color: var(--accent);
        text-decoration: none;
        font-weight: 600;
      }
      .card a:hover {
        text-decoration: underline;
      }
      code {
        font-family: "IBM Plex Mono", "SFMono-Regular", monospace;
      }
    </style>
  </head>
  <body>
    <main>
      <h1>ad-tensors-rs Documentation</h1>
      <p>API documentation generated by <code>cargo doc</code>.</p>
      <div class="card">
        <h2>API</h2>
        <p>Open crate documentation and module index.</p>
        <a href="./api/index.html">Open API index</a>
      </div>
    </main>
  </body>
</html>
TOPPAGE

echo "Done: $OUT_DIR"
