#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
OUT_DIR="${1:-$ROOT_DIR/target/docs-site}"
API_DIR="$OUT_DIR/api"

rm -rf "$OUT_DIR"
mkdir -p "$API_DIR"

echo "[1/5] Building rustdoc"
rm -rf "$ROOT_DIR/target/doc"
cargo doc --workspace --no-deps

echo "[2/5] Copying rustdoc output"
cp -a "$ROOT_DIR/target/doc/." "$API_DIR/"

echo "[3/5] Generating API index"
crate_links=""
while IFS= read -r crate_dir; do
  crate_name="$(basename "$crate_dir")"
  if [ "$crate_name" = "src" ]; then
    continue
  fi
  if [ ! -f "$crate_dir/index.html" ]; then
    continue
  fi
  printf -v crate_links '%s        <li><a href="./%s/index.html">%s</a></li>\n' \
    "$crate_links" "$crate_name" "$crate_name"
done < <(find "$API_DIR" -mindepth 1 -maxdepth 1 -type d | sort)

OVERVIEW_HTML=""
API_INDEX_MD="$ROOT_DIR/docs/api_index.md"
if [ -f "$API_INDEX_MD" ]; then
  if command -v pandoc >/dev/null 2>&1; then
    OVERVIEW_HTML=$(pandoc "$API_INDEX_MD" -f gfm -t html5)
  else
    if [ "${CI:-}" = "true" ]; then
      echo "pandoc is required in CI to render docs/api_index.md."
      exit 1
    fi
    echo "Warning: pandoc not found; overview section will be plain text."
    OVERVIEW_HTML="<pre>$(sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g' "$API_INDEX_MD")</pre>"
  fi
fi

{
  cat <<'HEADER'
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>ad-tensors-rs API docs</title>
    <style>
      body { font-family: "IBM Plex Sans", "Segoe UI", sans-serif; margin: 2rem auto; max-width: 56rem; padding: 0 1rem; color: #14213d; }
      h1 { margin-bottom: 0.5rem; }
      h2 { margin-top: 2rem; color: #2a3658; }
      p { color: #3c4a6b; line-height: 1.6; }
      ul { line-height: 1.8; }
      a { color: #005bb5; text-decoration: none; }
      a:hover { text-decoration: underline; }
      code { font-family: "IBM Plex Mono", "SFMono-Regular", monospace; }
    </style>
  </head>
  <body>
HEADER

  if [ -n "$OVERVIEW_HTML" ]; then
    echo "$OVERVIEW_HTML"
  fi

  cat <<CRATES
    <h2>Crates</h2>
    <ul>
$crate_links    </ul>
CRATES

  cat <<'FOOTER'
  </body>
</html>
FOOTER
} >"$API_DIR/index.html"

echo "[4/5] Rendering design docs with Quarto"
if command -v quarto >/dev/null 2>&1; then
  quarto render "$ROOT_DIR/docs"
else
  echo "Warning: quarto not found; design docs site skipped."
  if [ "${CI:-}" = "true" ]; then
    echo "quarto is required in CI to render design docs."
    exit 1
  fi
fi

echo "[5/5] Generating top page"
cat <<'TOPPAGE' >"$OUT_DIR/index.html"
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>ad-tensors-rs docs</title>
    <style>
      :root {
        --bg: #f6f8fb;
        --fg: #14213d;
        --muted: #3c4a6b;
        --accent: #005bb5;
        --card: #ffffff;
        --line: #d9e1ef;
      }
      body {
        margin: 0;
        color: var(--fg);
        font-family: "IBM Plex Sans", "Segoe UI", sans-serif;
        background: radial-gradient(circle at top right, #eef4ff, var(--bg) 60%);
      }
      main {
        max-width: 880px;
        margin: 0 auto;
        padding: 44px 20px 56px;
      }
      h1 {
        margin: 0 0 10px;
        font-size: 2rem;
      }
      p {
        margin: 0 0 10px;
        color: var(--muted);
        line-height: 1.55;
      }
      .grid {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
        gap: 14px;
        margin-top: 26px;
      }
      .card {
        border: 1px solid var(--line);
        border-radius: 10px;
        background: var(--card);
        padding: 16px;
      }
      .card h2 {
        margin: 0 0 8px;
        font-size: 1.1rem;
      }
      .card a {
        color: var(--accent);
        text-decoration: none;
        font-weight: 600;
      }
      .card a:hover {
        text-decoration: underline;
      }
      code {
        font-family: "IBM Plex Mono", "SFMono-Regular", monospace;
      }
    </style>
  </head>
  <body>
    <main>
      <h1>ad-tensors-rs Documentation</h1>
      <p>Unified entry point for API docs and design documents.</p>
      <div class="grid">
        <section class="card">
          <h2>API</h2>
          <p>Rust API docs generated by <code>cargo doc</code>.</p>
          <a href="./api/index.html">Open API index</a>
        </section>
        <section class="card">
          <h2>Design</h2>
          <p>Rendered architecture and design documents.</p>
          <a href="./design/">Open design docs</a>
        </section>
      </div>
    </main>
  </body>
</html>
TOPPAGE

echo "Done: $OUT_DIR"
